logging_file_path: "debug.log"

train_data_location: "dataset/train.csv"
performance_reporting_data_location: "dataset/test.csv"
sample_submission_data_location: "dataset/sample_submission.csv"


training_columns: ['MonsoonIntensity', 'TopographyDrainage', 'RiverManagement','Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
                  'Siltation', 'AgriculturalPractices', 'Encroachments','IneffectiveDisasterPreparedness', 'DrainageSystems',
                  'CoastalVulnerability', 'Landslides', 'Watersheds','DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
                  'InadequatePlanning', 'PoliticalFactors']
target_column: "FloodProbability"



